<a href="https://colab.research.google.com/github/github-somu/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

my_list = [1,2,3,4,5]
my_list




[1, 2, 3, 4, 5]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.12578085, 0.42436271, 0.65905053, 0.30207105],
       [0.85229719, 0.10763228, 0.14510419, 0.30392203],
       [0.58870095, 0.45284124, 0.15014099, 0.17936677]])

In [4]:
torch1 = torch.rand(3,4)
torch1

tensor([[0.1646, 0.7100, 0.2190, 0.0514],
        [0.8867, 0.8488, 0.2354, 0.6571],
        [0.4823, 0.4997, 0.0411, 0.9845]])

In [16]:
my_torch = torch.arange(10)
my_torch2 = my_torch.reshape(2,5)
print(my_torch2)
my_torch3 = my_torch2[:,2:3]
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


tensor([[2],
        [7]])

In [23]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([6,7,8,9])

tensor_ab = tensor_b + tensor_a




tensor([ 7,  9, 11, 13])

In [ ]:
## Basic neural network
